/*
GeeksforGeeks: Stack Operations
Difficulty: Easy

Problem:
Implement a class myStack that supports following operations:
- void push(int x): Insert an element x at the top of the stack.
- void pop(): Remove the element from the top of the stack.
- int peek(): Return the element currently at the top of the stack.
- bool isEmpty(): Return true if the stack is empty, otherwise false.
- int getSize(): Return the number of elements currently in the stack.

Example 1:
Input: arr[] = [[1 10], [1 30], [3], [5], [2], [4]]
Output: [30, 2, false]
Explanation: 
push(10) into the stack.
push(30) into the stack.
Return top of the stack, i.e. 30.
Return current size of the stack, i.e. 2.
Remove the element from the top of the stack
Stack is non-empty, i.e. return false.

Core Idea:
This is a standard implementation of a Stack data structure. We can achieve this elegantly by utilizing the standard C++ library's `std::stack` internally, wrapping its methods to match the expected interface, or by using a simple array/vector. Here we'll wrap `std::stack` for robust and clean code.

Approach:
1. Declare a private `std::stack<int> st` as the underlying storage.
2. `push(x)`: Call `st.push(x)`.
3. `pop()`: Check if the stack is not empty, then call `st.pop()`.
4. `peek()`: Check if the stack is empty (return a dummy value like -1 if so), otherwise return `st.top()`.
5. `isEmpty()`: Return `st.empty()`.
6. `getSize()`: Return `st.size()`.

Time Complexity: O(1) for all operations.
Space Complexity: O(N) to store N elements in the stack.

GFG Link:
https://www.geeksforgeeks.org/problems/stack-operations/1
*/

#include <iostream>
#include <stack>

using namespace std;

class myStack {
private:
    stack<int> st;

public:
    // Insert an element x at the top of the stack.
    void push(int x) {
        st.push(x);
    }
    
    // Remove the element from the top of the stack.
    void pop() {
        if (!st.empty()) {
            st.pop();
        }
    }
    
    // Return the element currently at the top of the stack.
    int peek() {
        if (st.empty()) {
            return -1; 
        }
        return st.top();
    }
    
    // Return true if the stack is empty, otherwise false.
    bool isEmpty() {
        return st.empty();
    }
    
    // Return the number of elements currently in the stack.
    int getSize() {
        return st.size();
    }
};

/*
Dry Run — Example 1:
Queries: [[1 10], [1 30], [3], [5], [2], [4]]

Initial State: st = []

Query 1: [1 10] -> push(10)
st = [10]

Query 2: [1 30] -> push(30)
st = [10, 30] (top is 30)

Query 3: [3] -> peek()
st.top() is 30. Returns 30.

Query 4: [5] -> getSize()
st.size() is 2. Returns 2.

Query 5: [2] -> pop()
st.pop() executed. 
st = [10] (top is 10)

Query 6: [4] -> isEmpty()
st.empty() is false. Returns false.

Final Output generated by driver: [30, 2, false]
*/
