/*
Problem: Operations on Stack

GFG: https://www.geeksforgeeks.org/problems/operations-on-stack/1

Description:
Given Q stack queries, perform operations:
- "i x": push x
- "r"  : pop top
- "h"  : report top
- "f y": check if y exists in stack ("Yes"/"No")

Return outputs generated by "h" and "f" queries.

Examples:
Q = 6, queries = [i 2, i 4, i 3, i 5, h, f 8]
Output: 5, No

Q = 4, queries = [i 3, i 4, r, f 3]
Output: Yes

Constraints:
1 <= queries.size() <= 10^3

Approach:
Use a stack<int> for push/pop/top.
For "f y", check presence by copying stack to temp and scanning.

Time Complexity:
- push/pop/top: O(1)
- find query: O(N) in current stack size
Overall depends on query mix.

Space Complexity: O(N)

Pattern: Stack Simulation
*/

#include <bits/stdc++.h>
using namespace std;

class Solution {
  public:
    vector<string> performQueries(vector<vector<string>>& queries) {
        stack<int> st;
        vector<string> ans;

        for (auto &q : queries) {
            if (q[0] == "i") {
                int x = stoi(q[1]);
                st.push(x);
            } 
            else if (q[0] == "r") {
                if (!st.empty()) {
                    st.pop();
                }
            } 
            else if (q[0] == "h") {
                if (!st.empty()) {
                    ans.push_back(to_string(st.top()));
                }
            } 
            else if (q[0] == "f") {
                int y = stoi(q[1]);
                bool found = false;

                stack<int> temp = st;
                while (!temp.empty()) {
                    if (temp.top() == y) {
                        found = true;
                        break;
                    }
                    temp.pop();
                }

                ans.push_back(found ? "Yes" : "No");
            }
        }

        return ans;
    }
};

