/*
    Problem Name: Clone a Binary Tree
    Difficulty: Medium
    Platform: GeeksforGeeks

    Problem Statement:
    A special binary tree is given where each node contains a `random` pointer along with the usual
    `left` and `right` child pointers. Clone the given binary tree (create a deep copy).

    Note:
    - The output generated by driver code is 1 if the tree is cloned successfully, otherwise 0.
    - Node structure includes `int data`, `Node* left`, `Node* right`, and `Node* random`.

    Examples:
    Input:
               1
             /   \
            2     3
           / \
          4   5
    (With random pointers e.g., 1->random = 3, 2->random = 1, 4->random = 5)

    Output: Cloned tree root (Deep copy of all nodes and pointers).

    Constraints:
    1 <= number of nodes <= 10^5
    1 <= node->data <= 10^5

    Expected Complexities:
    Time Complexity: O(N), where N is the number of nodes. 2 DFS passes over the tree.
    Space Complexity: O(N), for the hash map mapping original nodes to cloned nodes.

    Love Babbar Style Approach:
    Hash Map Node Mapping (Pass 1: Node Cloning, Pass 2: Random Pointer Linking):

    1. INTUITION:
       - Since `random` pointers can point to any arbitrary node (including future/unvisited nodes),
         we cannot link `random` pointers in a single pass directly without creating the target node first.
       - Pass 1: Perform DFS to create duplicate nodes for every original node and construct `left` & `right` pointers.
         * Maintain an `unordered_map<Node*, Node*> mp` where `mp[originalNode] = clonedNode`.
       - Pass 2: Perform DFS to assign `clonedNode->random = mp[originalNode->random]`.
       - Pass `mp` by reference to keep the solution clean with zero global/class state variables.

    2. ALGORITHM:
       - `cloneNodes(root, mp)`:
         * `if (root == NULL) return NULL;`
         * `Node* clone = new Node(root->data);`
         * `mp[root] = clone;`
         * `clone->left = cloneNodes(root->left, mp);`
         * `clone->right = cloneNodes(root->right, mp);`
         * Return `clone`.
       - `copyRandomPointers(root, mp)`:
         * `if (root == NULL) return;`
         * `if (root->random) mp[root]->random = mp[root->random];`
         * `copyRandomPointers(root->left, mp);`
         * `copyRandomPointers(root->right, mp);`
       - `cloneTree(root)`:
         * `unordered_map<Node*, Node*> mp;`
         * `Node* clonedRoot = cloneNodes(root, mp);`
         * `copyRandomPointers(root, mp);`
         * Return `clonedRoot`.

    Dry Run:
    original: 1 (rand=3) -> left: 2 (rand=1), right: 3

    - Pass 1:
      mp[1] = clone(1), mp[2] = clone(2), mp[3] = clone(3)
      clone(1)->left = clone(2), clone(1)->right = clone(3)
    - Pass 2:
      clone(1)->random = mp[3] = clone(3)
      clone(2)->random = mp[1] = clone(1)

    Deep copy created successfully ✓
*/

#include <iostream>
#include <unordered_map>

using namespace std;

// Definition for a binary tree node with random pointer.
struct Node {
    int data;
    Node* left;
    Node* right;
    Node* random;

    Node(int val) {
        data = val;
        left = right = random = NULL;
    }
};

class Solution {
private:
    // Pass 1: Deep copy node values and left/right structure, map original -> clone in mp
    Node* cloneNodes(Node* root, unordered_map<Node*, Node*>& mp) {
        if (root == NULL) return NULL;

        // Create duplicate node
        Node* cloneRoot = new Node(root->data);
        mp[root] = cloneRoot;

        // Recursively clone left and right subtrees
        cloneRoot->left = cloneNodes(root->left, mp);
        cloneRoot->right = cloneNodes(root->right, mp);

        return cloneRoot;
    }

    // Pass 2: Link random pointers for cloned nodes using mp
    void copyRandomPointers(Node* root, unordered_map<Node*, Node*>& mp) {
        if (root == NULL) return;

        // Set random pointer of cloned node to corresponding cloned random node
        if (root->random != NULL) {
            mp[root]->random = mp[root->random];
        }

        // Recurse left and right subtrees
        copyRandomPointers(root->left, mp);
        copyRandomPointers(root->right, mp);
    }

public:
    // GFG Signature
    Node* cloneTree(Node* root) {
        if (!root) return NULL;

        unordered_map<Node*, Node*> mp;

        // Step 1: Clone tree structure and build mapping
        Node* clonedRoot = cloneNodes(root, mp);

        // Step 2: Wire up random pointers in cloned tree
        copyRandomPointers(root, mp);

        return clonedRoot;
    }
};

// Helper function to verify deep clone correctness
bool verifyClone(Node* orig, Node* clone, unordered_map<Node*, Node*>& mp) {
    if (!orig && !clone) return true;
    if (!orig || !clone) return false;

    // Check data and unique memory address
    if (orig->data != clone->data || orig == clone) return false;

    // Check random pointer mapping
    if (orig->random != NULL) {
        if (clone->random != mp[orig->random]) return false;
    } else {
        if (clone->random != NULL) return false;
    }

    return verifyClone(orig->left, clone->left, mp) &&
           verifyClone(orig->right, clone->right, mp);
}

int main() {
    Solution ob;

    // Example Tree Creation with Random Pointers:
    //            1 (rand -> 3)
    //          /   \
    //         2     3 (rand -> 1)
    //        / \
    //       4   5 (rand -> 2)
    Node* root = new Node(1);
    root->left = new Node(2);
    root->right = new Node(3);
    root->left->left = new Node(4);
    root->left->right = new Node(5);

    // Wire random pointers
    root->random = root->right;       // 1 -> 3
    root->right->random = root;        // 3 -> 1
    root->left->right->random = root->left; // 5 -> 2

    // Clone tree
    Node* clonedRoot = ob.cloneTree(root);

    // Verify Clone
    unordered_map<Node*, Node*> mapVerification;
    // Helper check
    cout << "Clone Status: " << (clonedRoot != NULL ? "Success (1)" : "Failure (0)") << "\n";

    return 0;
}
